# Generated by Django 3.2.9 on 2021-11-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaRacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silo_id', models.IntegerField(blank=True)),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='flow(kg/s)')),
                ('datetime_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
