# Generated by Django 3.2.9 on 2021-11-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensoriamento', '0002_auto_20211114_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaracao',
            name='chave',
            field=models.IntegerField(blank=True, null=True, verbose_name='pk'),
        ),
        migrations.AlterField(
            model_name='entregaracao',
            name='weight_entrega',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso(kg/s)'),
        ),
    ]
